run:
  # timeout for analysis
  deadline: 10m

linters-settings:
  govet:
    # Don't report about shadowed variables
    check-shadowing: false
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true

linters:
  disable-all: true
  enable:
    - asciicheck
    - deadcode
    - dupl
    - errcheck
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - nolintlint
    - prealloc
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    
    # Others to consider that do not pass presently:
    # - nilerr
    # - makezero

issues:
  exclude-rules:
    # Exclude gosec from running for tests so that tests with weak randomness
    # (math/rand) will pass the linter.
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - dupl
